Add debug

diff --git a/set_up_py-youwol_integration/action.yml b/set_up_py-youwol_integration/action.yml
--- a/set_up_py-youwol_integration/action.yml
+++ b/set_up_py-youwol_integration/action.yml
@@ -1,45 +1,48 @@
 name: Set up PyYouwol Integration Testing
 description: Set up & launch py-youwol for integration testing
 inputs:
-  pyYouwolRef:
+  src_ref:
     description: Git ref for py-youwol checkout
     required: false
     default: master
-  integrationTestsRef:
+  conf_ref:
     description: Git ref for integration-tests-conf checkout
     required: false
     default: main
 outputs:
-  shutdownScript:
+  shutdown_script:
     description: path to the shutdown script
-    value: ${{ steps.summary.outputs.shutdown_script_path }}
+    value: ${{ steps.summary.outputs.shutdown_script }}
+  src_dir:
+    description: path to py-youwol source directory
+    value: ${{ steps.summary.outputs.src_dir }}
+  conf_dir:
+    description: path to configuration directory
+    value: ${{ steps.summary.outputs.conf_dir }}
+  work_dir:
+    description: path to working directory
+    value: ${{ steps.summary.outputs.work_dir }}
 
 runs:
   using: 'composite'
   steps:
-###### Prepare environnement variables
-    # $GITHUB_ENV is a file managed by Github Actions
-    # This environnement variables will be available during the whole workflow
-    # - py_it_dir : Path of the directory containing everything pertaining to py-youwol integration testing
-    # - py_it_src_dir : Path of the sources of py-youwol
-    # - py_it_conf_dir : Path of the configuration use for integration testing
-    # - py_it_shutdown_script : Path of the shell script for stopping the running py-youwol instance
-    - name: Set up actions variables
+    - name: Set up action variables
       id: set_up_vars
       run: |
         ### Set up action variables
         echo "::group::make working directory"
-        working_dir="${RUNNER_TEMP}/py-youwoul-integration/$(base64 <<<$RANDOM)"
-        mkdir "${working_dir}"
+        random=$(awk 'BEGIN { srand(); print int(rand()*32768) }' /dev/null | base64)
+        working_dir="${RUNNER_TEMP}/py-youwoul-integration/${random}"
+        mkdir -p "${working_dir}"
         echo "::endgroup::"
         #
         echo "::group::outputs"
         echo "::set-output name=working_dir::${working_dir}"
         echo "::set-output name=src_dir::$GITHUB_WORKSPACE/.py-youwol-integration/py-youwol"
         echo "::set-output name=conf_dir::$GITHUB_WORKSPACE/.py-youwol-integration/it-conf"
-        echo "::set-output name=shutdown_script_path=${working_dir}/py-youwol.shutdown.sh" 
+        echo "::set-output name=shutdown_script::${working_dir}/py-youwol.shutdown.sh" 
         echo "::endgroup::"
-      shell: bash
+      shell: sh
 
 ###### Checkout repositories
     # Checkout py-youwol into $py_it_src_dir, using the ref from input pyYouwolRef
@@ -48,16 +51,16 @@ runs:
       uses: actions/checkout@v3
       with:
         repository: youwol/py-youwol
-        ref: ${{ inputs.pyYouwolRef }}
-        path: ${{ steps.set_up_vars.output.src_dir }}
+        ref: ${{ inputs.src_ref }}
+        path: ${{ steps.set_up_vars.outputs.src_dir }}
     # Checkout the integration testing conf into $py_it_conf_dir, using the ref from input integrationTestsRef
     - name: Checkout integration tests configuration repo
       id: checkout_it_conf
       uses: actions/checkout@v3
       with:
         repository: youwol/integration-tests-conf
-        ref: ${{ inputs.integrationTestsRef }}
-        path: ${{ steps.set_up_vars.output.conf_dir }}
+        ref: ${{ inputs.conf_ref }}
+        path: ${{ steps.set_up_vars.outputs.conf_dir }}
 
 ###### Setup python & dependencies
     - name: Setup Python 3.9
@@ -68,10 +71,9 @@ runs:
         cache: 'pip'
     - name: Install dependencies
       id: install_python_dep
-      env:
-        src_dir: ${{ steps.set_up_vars.outputs.src_dir }}
-      run: pip install -r ${src_dir}/requirements.txt
-      shell: bash
+      working-directory: ${{ steps.set_up_vars.outputs.src_dir }}
+      run: pip install -r requirements.txt
+      shell: sh
 
 ###### Launch py-youwol
     # Launching py-youwol
@@ -79,13 +81,13 @@ runs:
     # PYTHONPATH is defined only for this step, so it does not pollute other steps or jobs
     - name: Launch py-youwol
       id: launch_py_youwol
+      working-directory: ${{ steps.set_up_vars.outputs.working_dir }}
       env:
-        PYTHONPATH: ${{ steps…set_up_var.outputs.src_dir }}
+        PYTHONPATH: ${{ steps.set_up_vars.outputs.src_dir }}
         src_dir: ${{ steps.set_up_vars.outputs.src_dir }}
         conf_dir: ${{ steps.set_up_vars.outputs.conf_dir }}
-      working-directory: ${{ steps.set_up_var.outputs.working_dir }}
-      run: python3 -u ${src_dir}/youwol/main.py --conf ${conf_dir}/yw_config_IT.py --daemonize &
-      shell: bash
+      run: python3 -u ${src_dir}/youwol/main.py --conf ${conf_dir}/yw_config_IT.py > py-youwol.out 2> py-youwol.err &
+      shell: sh
     # Try at most 10 times to call healtz endpoint, checking its response, and waiting 1 second between retries
     - name: Wait for running instance
       id: wait_py_youwol_running
@@ -96,21 +98,35 @@ runs:
         echo "::group::Trying at most 10 times to call healtz endpoint, waiting 1 seconde between retries"
         for try in $(seq 1 1 10); do
           echo "try $try/10 to contact py-youwol instance"
-          curl --silent http://localhost:2001/healthz | jq -e "${jq_cmd}" && exit 0
-          sleep 1
+          response=$(curl --silent http://localhost:2001/healthz || echo "No response")
+          echo "Response : '${response}'"
+          if echo "${response}" | jq -e "${jq_cmd}"; then
+            exit 0
+          else
+            echo "Invalid response. Retrying in 1 second"
+            sleep 1
+          fi
         done
         #
         echo "::endgroup::"
         echo "::error ::Failed to contact py-youwol instance after 10 seconds"
         exit 1
-      shell: bash
+      shell: sh
     # Finally, some annotated logging about how everything is configured
     - name: Summary
       id: summary
       env:
-        shutdown_script_path: ${{ steps.set_up_vars.outputs.shutdown_script_path }}
+        src_ref: ${{ inputs.scr_ref }}
+        conf_ref: ${{ inputs.conf_ref }}
+        shutdown_script: ${{ steps.set_up_vars.outputs.shutdown_script }}
+        src_dir: ${{ steps.set_up_vars.outputs.src_dir }}
+        conf_dir: ${{ steps.set_up_vars.outputs.conf_dir }}
+        work_dir: ${{ steps.set_up_vars.outputs.working_dir }}
       run: |
         ### Log summary
-        echo "::notice title=Py-Youwol Integration Testing::youwol/py-youwol@${{ inputs.pyYouwolRef}} running with configuration from youwol/integration-tests-conf@${{ inputs.integrationTestsRef }}"
-        echo "::set-output name=shutdown_script_path::${shutdown_script_path}"
-      shell: bash
+        echo "::notice title=Py-Youwol Integration Testing::youwol/py-youwol@${src_ref} running with configuration from youwol/integration-tests-conf@${conf_ref}"
+        echo "::set-output name=shutdown_script::${shutdown_script}"
+        echo "::set-output name=src_dir::${src_dir}"
+        echo "::set-output name=conf_dir::${conf_dir}"
+        echo "::set-output name=work_dir::${work_dir}"
+      shell: sh
